### ISSUE TITLE
Can't get this to work because it requires node core modules

### ISSUE THREAD

**Issue by jholton** [perry-mitchell/react-native-dropbox-sdk#1]
Hi,

I'm trying to use this, but I get errors immediately.
If I include
`import Dropbox from 'react-native-dropbox-sdk';`
I get 
`Unable to resolve module 'url' from ./node_modules/node-fetch/index.js:  Module does not exist in the module map`

'url' is a node core module, which is not usable inside React-Native.

How do you get around this?

**Comment by perry-mitchell** [comment]
Hi @jholton - Sorry I hadn't updated this project sooner, but I've moved away from trying to support dropbox in the React-Native side. There are too many low-level components Dropbox requires (UInt8 arrays, Buffers/Blobs etc.) that RN just doesn't have. I was not able to get this working correctly in every case, so I'll most likely add Dropbox to my existing project by adding Objective-C/Java code.

**Comment by perry-mitchell** [comment]
But to quickly address your issue - It looks like you installed `react-native-dropbox-sdk`, but perhaps you're not using rn-nodeify? I've used it several times to "hack in" several necessary core modules. I've used it [here](https://github.com/buttercup/buttercup-mobile/blob/master/package.json#L6).

I apologise for misleading you..

**Comment by jholton** [comment]
Thanks for the info!
